USE CASESTUDY;

DROP TABLE BOOK;

CREATE TABLE BOOK(ISBNNUMBER INT PRIMARY KEY AUTO_INCREMENT, BOOKNAME VARCHAR(20),AUTHORNAME VARCHAR(20),EDITION INT);

INSERT INTO BOOK(BOOKNAME,AUTHORNAME,EDITION) VALUES (?,?,?)

SELECT * FROM BOOK WHERE ISBNNUMBER=?

UPDATE BOOK SET  EDITION =? where ISBNNUMBER= ?

DELETE FROM BOOK WHERE ISBNNUMBER=?